import {createProject,addNode,addBoxPort,removeNode,connect,defFor,NODE_DEFS,serializeProject,deserializeProject,breadcrumbs,parentPatchId,wrapNodesInSubpatch,touch} from '../shared/graph.js';
import {RuntimeEngine} from '../shared/runtime-core.js';
import {planVibe,applyVibePlan,graphSummary} from '../shared/vibe.js';
import {exportMax,exportTouchDesigner} from '../shared/exporters.js';
const $=s=>document.querySelector(s),native=window.nodeVibeNative||{},hasNative=!!window.nodeVibeNative;
let project=createProject('Nouveau projet'),patchId=project.rootPatchId,sel=new Set(),pending=null,zoom=1,history=[],future=[],busy=false,lastVisual=null,cue=-1,stream=null,video=null,midi=null,midiVal=new Map(),serialVal={value:0,text:''};const sent=new Map();
let runtime=makeRuntime();
function makeRuntime(){return new RuntimeEngine(project,{effects:{cameraFrame:n=>({kind:'camera',nodeId:n.id,active:!!n.params.active}),midiValue:n=>midiVal.get(n.id)||{value:0,velocity:0},serialValue:()=>serialVal,sendOsc:oscEffect,sendArtNet:artEffect}});}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function log(m,t=''){let e=document.createElement('div');e.className='log-line '+t;e.textContent='['+new Date().toLocaleTimeString('fr-FR',{hour12:false})+'] '+m;$('#log').append(e);$('#log').scrollTop=$('#log').scrollHeight;}
function snap(){history.push(serializeProject(project));if(history.length>50)history.shift();future=[];}
function auto(){project.workspace.currentPatchId=patchId;project.workspace.zoomByPatch[patchId]=zoom;localStorage.setItem('node-vibe-autosave-v2',serializeProject(project));}
function changed(m){touch(project);auto();render();if(m)log(m,'success');}
function restore(s){project=deserializeProject(s);patchId=project.workspace.currentPatchId||project.rootPatchId;runtime=makeRuntime();sel.clear();render();}
function render(){library();canvas();inspector();cues();}
function library(){let q=$('#librarySearch').value.toLowerCase(),r=$('#libraryList');r.innerHTML='';let g={};Object.entries(NODE_DEFS).forEach(([k,d])=>{if(d.internal||q&&!((d.label+' '+d.category+' '+k).toLowerCase().includes(q)))return;(g[d.category]??=[]).push([k,d]);});Object.entries(g).forEach(([cat,arr])=>{let h=document.createElement('div');h.className='lib-section';h.textContent=cat;r.append(h);arr.forEach(([type,d])=>{let x=document.createElement('div');x.className='lib-item';x.innerHTML='<span>'+esc(d.label)+'</span><em>＋</em>';x.onclick=()=>{snap();let n=addNode(project,patchId,type,{x:90+Math.random()*180,y:80+Math.random()*140});sel=new Set([n.id]);changed('Node créé · '+d.label)};r.append(x);});});}
function portHTML(n,p,dir){return '<div class="port '+dir+'" data-node="'+n.id+'" data-port="'+esc(p[0])+'" data-dir="'+dir+'">'+(dir==='in'?'<span class="port-dot"></span>':'')+'<span class="port-label">'+esc(p[2]||p[0])+'</span>'+(dir==='out'?'<span class="port-dot"></span>':'')+'</div>';}
function canvas(){let p=project.patches[patchId],nl=$('#nodeLayer');nl.innerHTML='';$('#wireLayer').innerHTML='';$('#canvasWorld').style.transform='scale('+zoom+')';$('#zoomLabel').textContent=Math.round(zoom*100)+'%';p.nodes.forEach(n=>{let d=defFor(project,n),e=document.createElement('div');e.className='node '+(n.type==='subpatch'?'subpatch ':'')+(sel.has(n.id)?'selected':'');e.dataset.id=n.id;e.style.left=n.x+'px';e.style.top=n.y+'px';e.innerHTML='<div class="node-head">'+esc(n.name)+'</div><div class="node-ports"><div class="ports-col">'+(d.inputs||[]).map(x=>portHTML(n,x,'in')).join('')+'</div><div class="ports-col">'+(d.outputs||[]).map(x=>portHTML(n,x,'out')).join('')+'</div></div>';nl.append(e);bindNode(e,n);});requestAnimationFrame(wires);crumbs();buttons();}
function bindNode(e,n){e.onclick=x=>{if(x.target.closest('.port'))return;if(x.shiftKey){sel.has(n.id)?sel.delete(n.id):sel.add(n.id)}else sel=new Set([n.id]);canvas();inspector();};e.ondblclick=()=>{if(n.type==='subpatch')enter(n.subpatchId)};let h=e.querySelector('.node-head');h.onpointerdown=x=>{x.preventDefault();if(!sel.has(n.id))sel=new Set([n.id]);snap();let items=[...sel].map(id=>{let z=project.patches[patchId].nodes.find(a=>a.id===id);return {z,x:z.x,y:z.y}}),sx=x.clientX,sy=x.clientY;h.setPointerCapture(x.pointerId);h.onpointermove=y=>{items.forEach(i=>{i.z.x=Math.round(i.x+(y.clientX-sx)/zoom);i.z.y=Math.round(i.y+(y.clientY-sy)/zoom)});canvas();};h.onpointerup=()=>{h.onpointermove=null;h.onpointerup=null;changed();};};e.querySelectorAll('.port').forEach(p=>p.onclick=x=>{x.stopPropagation();wirePort(p.dataset.node,p.dataset.port,p.dataset.dir)});}
function wirePort(n,p,d){if(!pending){if(d!=='out')return hint('Commence par une sortie.');pending={n,p};return hint('Choisis une entrée compatible.')}if(d!=='in'){pending={n,p};return hint('Nouvelle sortie sélectionnée.')}snap();try{connect(project,patchId,pending.n,pending.p,n,p);log('Connexion créée.','success')}catch(e){log(e.message,'error');hint(e.message)}pending=null;changed();}
function hint(m){let e=$('#connectionHint');e.textContent=m;e.classList.remove('hidden');clearTimeout(e.t);e.t=setTimeout(()=>e.classList.add('hidden'),1800)}
function wires(){let p=project.patches[patchId],svg=$('#wireLayer'),wr=$('#canvasWorld').getBoundingClientRect();svg.innerHTML='';p.connections.forEach(c=>{let a=document.querySelector('.port.out[data-node="'+CSS.escape(c.from.node)+'"][data-port="'+CSS.escape(c.from.port)+'"] .port-dot'),b=document.querySelector('.port.in[data-node="'+CSS.escape(c.to.node)+'"][data-port="'+CSS.escape(c.to.port)+'"] .port-dot');if(!a||!b)return;let ar=a.getBoundingClientRect(),br=b.getBoundingClientRect(),x1=(ar.left+4-wr.left)/zoom,y1=(ar.top+4-wr.top)/zoom,x2=(br.left+4-wr.left)/zoom,y2=(br.top+4-wr.top)/zoom,k=Math.max(35,Math.abs(x2-x1)/2),q=document.createElementNS('http://www.w3.org/2000/svg','path');q.setAttribute('class','wire');q.setAttribute('d','M '+x1+' '+y1+' C '+(x1+k)+' '+y1+', '+(x2-k)+' '+y2+', '+x2+' '+y2);svg.append(q)});}
function crumbs(){let b=$('#breadcrumbs');b.innerHTML='';breadcrumbs(project,patchId).forEach(c=>{let e=document.createElement('span');e.className='crumb';e.textContent=c.name;e.onclick=()=>enter(c.patchId);b.append(e)})}
function enter(id){if(!project.patches[id])return;patchId=id;project.workspace.currentPatchId=id;sel.clear();zoom=project.workspace.zoomByPatch[id]||1;render();log('Entré dans · '+project.patches[id].name)}
function inspector(){let b=$('#inspectorBody');$('#selectionCount').textContent=sel.size?sel.size+' sélectionné(s)':'';if(sel.size!==1){b.innerHTML=sel.size?'<p>'+sel.size+' nodes sélectionnés.</p><div class="inspector-actions"><button id="wrapBtn">Mettre dans une boîte</button></div>':'<p class="muted">Sélectionne un node.</p>';$('#wrapBtn')?.addEventListener('click',()=>{snap();let x=wrapNodesInSubpatch(project,patchId,[...sel],'Boîte');sel=new Set([x.id]);changed('Sous-patch créé.');});return}let n=project.patches[patchId].nodes.find(x=>x.id===[...sel][0]),d=defFor(project,n),html='<div class="status-card"><b>'+esc(n.name)+'</b><br><span class="muted">'+esc(n.type)+'</span></div><div class="field"><label>Nom</label><input data-name value="'+esc(n.name)+'"></div>';Object.entries(n.params||{}).forEach(([k,v])=>{if(k==='portId'||k==='dataType')return;html+='<div class="field"><label>'+esc(k)+'</label><input data-param="'+esc(k)+'" type="'+(typeof v==='number'?'number':'text')+'" value="'+esc(v)+'"></div>'});html+='<div class="port-list"><b>Entrées</b><br>'+((d.inputs||[]).map(x=>esc(x[2]||x[0])+' · '+esc(x[1])).join('<br>')||'—')+'<br><br><b>Sorties</b><br>'+((d.outputs||[]).map(x=>esc(x[2]||x[0])+' · '+esc(x[1])).join('<br>')||'—')+'</div>';if(n.type==='subpatch')html+='<div class="inspector-actions"><button id="enterBox">Entrer</button><button id="inPort">＋ entrée</button><button id="outPort">＋ sortie</button></div>';if(n.type==='camera')html+='<div class="inspector-actions"><button id="deviceBtn">Activer caméra</button></div>';if(n.type==='midi-in')html+='<div class="inspector-actions"><button id="deviceBtn">Connecter MIDI</button></div>';if(n.type==='serial-in')html+='<div class="inspector-actions"><button id="deviceBtn">Connecter Serial</button></div>';b.innerHTML=html;b.querySelector('[data-name]').onchange=e=>{snap();n.name=e.target.value||n.name;if(n.type==='subpatch')project.patches[n.subpatchId].name=n.name;changed('Node renommé.')};b.querySelectorAll('[data-param]').forEach(i=>i.onchange=()=>{snap();let old=n.params[i.dataset.param];n.params[i.dataset.param]=typeof old==='number'?Number(i.value):typeof old==='boolean'?i.value==='true':i.value;changed('Paramètre mis à jour.')});$('#enterBox')?.addEventListener('click',()=>enter(n.subpatchId));$('#inPort')?.addEventListener('click',()=>newPort(n,'input'));$('#outPort')?.addEventListener('click',()=>newPort(n,'output'));$('#deviceBtn')?.addEventListener('click',()=>n.type==='camera'?camera(n):n.type==='midi-in'?midiConnect(n):serialConnect(n));}
function newPort(n,d){let name=prompt('Nom du port',d==='input'?'In':'Out');if(!name)return;let type=prompt('Type : number, boolean, text, event, visual, any','number')||'any';snap();addBoxPort(project,n,d,name,type);changed('Port ajouté · '+name)}
async function camera(n){try{stream?.getTracks().forEach(t=>t.stop());stream=await navigator.mediaDevices.getUserMedia({video:true,audio:false});video??=document.createElement('video');video.srcObject=stream;video.autoplay=true;video.muted=true;await video.play();n.params.active=true;changed('Caméra connectée.')}catch(e){log('Caméra · '+e.message,'error')}}
async function midiConnect(n){try{midi=await navigator.requestMIDIAccess();for(const i of midi.inputs.values())i.onmidimessage=e=>{let s=e.data[0],ch=(s&15)+1;if(ch!==Number(n.params.channel||1))return;let k=s&240;if(k===176&&e.data[1]===Number(n.params.cc||1))midiVal.set(n.id,{value:e.data[2]/127,velocity:e.data[2]/127});else if(k===144)midiVal.set(n.id,{value:e.data[1],velocity:e.data[2]/127});};log('MIDI connecté · '+midi.inputs.size+' entrée(s).','success')}catch(e){log('MIDI · '+e.message,'error')}}
async function serialConnect(n){try{if(!navigator.serial)throw Error('Web Serial indisponible');let p=await navigator.serial.requestPort();await p.open({baudRate:Number(n.params.baudRate)||115200});let r=p.readable.getReader(),dec=new TextDecoder();log('Serial connecté.','success');(async()=>{while(true){let x=await r.read();if(x.done)break;let t=dec.decode(x.value),v=parseFloat(t);serialVal={text:t,value:Number.isFinite(v)?v:serialVal.value}}})()}catch(e){log('Serial · '+e.message,'error')}}
function cues(){let r=$('#cueList');r.innerHTML='';project.timeline.cues.forEach((c,i)=>{let e=document.createElement('div');e.className='cue '+(i===cue?'current':'');e.innerHTML='<span class="cue-index">'+(i+1)+'</span><div><b>'+esc(c.name)+'</b><small>'+esc(c.action.param)+' → '+esc(c.action.value)+'</small></div><button data-i="'+i+'">×</button>';r.append(e)});r.querySelectorAll('[data-i]').forEach(x=>x.onclick=()=>{snap();project.timeline.cues.splice(Number(x.dataset.i),1);changed('Cue supprimée.')})}
function addCue(){if(sel.size!==1)return log('Sélectionne un node pour créer une cue.','warn');let n=project.patches[patchId].nodes.find(x=>x.id===[...sel][0]),e=Object.entries(n.params).find(([,v])=>['number','string','boolean'].includes(typeof v));if(!e)return log('Aucun paramètre automatisable.','warn');let [param,old]=e,v=prompt('Valeur pour '+n.name+'.'+param,String(old));if(v===null)return;v=typeof old==='number'?Number(v):typeof old==='boolean'?v==='true':v;snap();project.timeline.cues.push({id:crypto.randomUUID(),name:n.name+' · '+param,action:{patchId,nodeId:n.id,param,value:v}});changed('Cue ajoutée.')}
function go(){if(!project.timeline.cues.length)return log('Aucune cue.','warn');cue=(cue+1)%project.timeline.cues.length;let c=project.timeline.cues[cue],n=project.patches[c.action.patchId]?.nodes.find(x=>x.id===c.action.nodeId);if(!n)return log('Cible de cue introuvable.','error');n.params[c.action.param]=c.action.value;render();log('GO '+(cue+1)+' · '+c.name,'success')}
async function vibe(){let text=$('#vibeText').value.trim();if(!text)return;$('#vibeStatus').textContent='Analyse…';snap();let plan=planVibe(text,project,patchId,[...sel]);try{if(!plan.operations.length&&native.vibeOllama){let r=await native.vibeOllama({prompt:text,graphSummary:graphSummary(project,patchId)});if(r?.ok&&Array.isArray(r.data?.operations))plan={operations:r.data.operations.map(o=>o.op?o:o.addNode?{op:'addNode',...o.addNode}:o.connect?{op:'connect',...o.connect}:o.setParam?{op:'setParam',...o.setParam}:o),explanation:r.data.explanation||('IA locale · '+r.model)};else if(r?.error)log('IA locale · '+r.error,'warn')}let out=applyVibePlan(plan,project,patchId,[...sel]);if(out.created.length)sel=new Set(out.created);changed(out.explanation||'Vibe appliquée.');$('#vibeStatus').textContent=out.explanation||'Patch modifié.'}catch(e){history.pop();log('Vibe · '+e.message,'error');$('#vibeStatus').textContent=e.message}}
async function oscEffect(n,v){if(!native.sendOsc)throw Error('OSC indisponible dans ce runtime : aucune passerelle UDP native n’est chargée');let k='o'+n.id;if(Object.is(sent.get(k),v))return;sent.set(k,v);let r=await native.sendOsc({host:n.params.host,port:n.params.port,address:n.params.address,args:[v]});if(r&&!r.ok)throw Error(r.error)}
async function artEffect(n,v){if(!native.sendArtNet)throw Error('Art-Net indisponible dans ce runtime : aucune passerelle UDP native n’est chargée');v=Math.max(0,Math.min(255,Math.round(Number(v)*255)));let k='a'+n.id;if(sent.get(k)===v)return;sent.set(k,v);let r=await native.sendArtNet({host:n.params.host,universe:n.params.universe,channel:n.params.channel,value:v});if(r&&!r.ok)throw Error(r.error)}
async function frame(t){if(!busy){busy=true;try{let r=await runtime.evaluate(project.rootPatchId,{}, {time:t/1000,dt:1/60,depth:0,stack:[]}),root=project.patches[project.rootPatchId],p=[...root.nodes].reverse().find(n=>n.type==='preview');lastVisual=p?r.values[project.rootPatchId+':'+p.id+':visual']:null;$('#engineStatus').textContent=r.errors.length?'● '+r.errors.length+' ERREUR(S)':'● ENGINE';$('#engineStatus').className=r.errors.length?'error-text':'ok'}catch(e){log('Engine · '+e.message,'error')}busy=false}draw(t/1000,lastVisual);requestAnimationFrame(frame)}
function draw(t,v){let c=$('#previewCanvas'),g=c.getContext('2d');g.fillStyle='#050607';g.fillRect(0,0,c.width,c.height);if(!v){g.fillStyle='#77808b';g.font='16px system-ui';g.fillText('Relie une sortie visuelle à Preview / OUTPUT',28,40);return}if(v.kind==='transform'){g.save();g.translate(c.width/2,c.height/2);g.rotate((v.rotation||0)*Math.PI/180);g.scale(v.scale||1,v.scale||1);g.translate(-c.width/2,-c.height/2);drawVisual(g,c,t,v.source);g.restore()}else drawVisual(g,c,t,v)}
function drawVisual(g,c,t,v){if(v?.kind==='camera'&&video?.readyState>=2)return g.drawImage(video,0,0,c.width,c.height);if(v?.kind!=='blackhole')return;let x=c.width/2,y=c.height/2,r=Math.min(c.width,c.height)*(v.size||.58)*.34,d=g.createRadialGradient(x,y,r*.6,x,y,r*2.4);d.addColorStop(0,'#000');d.addColorStop(.38,'#030305');d.addColorStop(.52,'#e5a652');d.addColorStop(.65,'#5d2842');d.addColorStop(1,'#050607');g.fillStyle=d;g.fillRect(0,0,c.width,c.height);g.save();g.translate(x,y);g.rotate(t*(v.speed||.65));g.globalCompositeOperation='screen';for(let i=0;i<60;i++){g.strokeStyle='rgba(255,'+(110+i%90)+',70,'+(.04+i%5/100)+')';g.beginPath();g.ellipse(0,0,r*(1.6+i%9/12),r*(.25+i%5/30),i*.07,0,5.5);g.stroke()}g.restore();g.fillStyle='#000';g.beginPath();g.arc(x,y,r*.7,0,7);g.fill()}
function duplicate(){if(!sel.size)return;snap();let p=project.patches[patchId],ns=[];[...sel].forEach(id=>{let n=p.nodes.find(x=>x.id===id);if(!n||n.type==='subpatch')return;ns.push(addNode(project,patchId,n.type,{name:n.name+' copie',x:n.x+25,y:n.y+25,params:structuredClone(n.params)}).id)});sel=new Set(ns);changed('Sélection dupliquée.')}
function del(){if(!sel.size)return;snap();[...sel].forEach(id=>removeNode(project,patchId,id));sel.clear();changed('Sélection supprimée.')}
function undo(){if(!history.length)return;future.push(serializeProject(project));restore(history.pop())}function redo(){if(!future.length)return;history.push(serializeProject(project));restore(future.pop())}
function buttons(){$('#parentBtn').disabled=!parentPatchId(project,patchId);$('#rootBtn').disabled=patchId===project.rootPatchId;$('#deleteBtn').disabled=!sel.size;$('#duplicateBtn').disabled=!sel.size}
function downloadText(name,data,type='application/octet-stream'){let blob=new Blob([data],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.style.display='none';document.body.append(a);a.click();setTimeout(()=>{URL.revokeObjectURL(url);a.remove()},1200);return {canceled:false,path:name}}
async function save(){let name=(project.name||'Projet')+'.nodevibe.json',data=serializeProject(project);if(native.saveProject){let r=await native.saveProject({suggestedName:name,data});if(r&&!r.canceled)log('Projet enregistré · '+r.path,'success');return}localStorage.setItem('node-vibe-manual-save-v2',data);auto();log('Projet enregistré localement dans No-de Vibe Designer.','success')}
async function openProject(){let r;if(native.openProject)r=await native.openProject();else{let saved=localStorage.getItem('node-vibe-manual-save-v2');if(saved&&confirm('Rouvrir le dernier projet enregistré localement ?'))r={canceled:false,path:'sauvegarde locale',data:saved};else r=await new Promise(resolve=>{let i=document.createElement('input');i.type='file';i.accept='.json,.nodevibe.json,application/json';i.style.display='none';document.body.append(i);i.onchange=async()=>{let f=i.files?.[0];if(!f){i.remove();return resolve({canceled:true})}try{resolve({canceled:false,path:f.name,data:await f.text()})}catch(e){resolve({canceled:true,error:e.message})}finally{i.remove()}};i.oncancel=()=>{i.remove();resolve({canceled:true})};i.click()})}if(r?.error)log('Ouverture · '+r.error,'error');if(r&&!r.canceled){history=[];future=[];restore(r.data);log('Projet ouvert · '+r.path,'success')}}
async function exportTo(kind){let o=kind==='max'?exportMax(project):exportTouchDesigner(project);if(o.unsupported.length)log('Non exportés · '+o.unsupported.join(', '),'warn');let name=kind==='max'?'No-de-export.maxpat':'No-de-import-touchdesigner.py',r=native.exportFile?await native.exportFile({suggestedName:name,data:o.content}):downloadText(name,o.content,'text/plain');if(r&&!r.canceled)log('Export créé · '+r.path,'success')}
$('#librarySearch').oninput=library;$('#parentBtn').onclick=()=>{let p=parentPatchId(project,patchId);if(p)enter(p)};$('#rootBtn').onclick=()=>enter(project.rootPatchId);$('#deleteBtn').onclick=del;$('#duplicateBtn').onclick=duplicate;$('#undoBtn').onclick=undo;$('#redoBtn').onclick=redo;$('#zoomInBtn').onclick=()=>{zoom=Math.min(2,zoom+.1);canvas()};$('#zoomOutBtn').onclick=()=>{zoom=Math.max(.35,zoom-.1);canvas()};$('#newBtn').onclick=()=>{if(confirm('Créer un nouveau projet ?')){project=createProject('Nouveau projet');patchId=project.rootPatchId;runtime=makeRuntime();sel.clear();render()}};$('#saveBtn').onclick=save;$('#openBtn').onclick=openProject;$('#exportMaxBtn').onclick=()=>exportTo('max');$('#exportTdBtn').onclick=()=>exportTo('td');$('#addCueBtn').onclick=addCue;$('#goBtn').onclick=go;$('#clearLogBtn').onclick=()=>$('#log').innerHTML='';$('#terminalToggle').onclick=()=>{$('#terminalPanel').classList.toggle('collapsed')};$('#vibeText').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();vibe()}};window.onkeydown=e=>{let m=e.metaKey||e.ctrlKey;if(m&&e.key==='s'){e.preventDefault();save()}else if(m&&e.key==='z'&&!e.shiftKey){e.preventDefault();undo()}else if(m&&e.key==='z'&&e.shiftKey){e.preventDefault();redo()}else if((e.key==='Delete'||e.key==='Backspace')&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName))del()};

window.__nodeVibeSelfTest=async()=>{try{
  let p=createProject('packaged-self-test'),root=p.patches[p.rootPatchId],src=addNode(p,root.id,'number',{params:{value:3}}),
      A=addNode(p,root.id,'subpatch',{name:'A'}),ai=addBoxPort(p,A,'input','in','number'),ao=addBoxPort(p,A,'output','out','number');
  connect(p,root.id,src.id,'value',A.id,ai.portId);
  let ap=p.patches[A.subpatchId],B=addNode(p,ap.id,'subpatch',{name:'B'}),bi=addBoxPort(p,B,'input','in','number'),bo=addBoxPort(p,B,'output','out','number');
  connect(p,ap.id,ai.node.id,'out',B.id,bi.portId);connect(p,ap.id,B.id,bo.portId,ao.node.id,'in');
  let bp=p.patches[B.subpatchId],mul=addNode(p,bp.id,'multiply'),two=addNode(p,bp.id,'number',{params:{value:2}});
  connect(p,bp.id,bi.node.id,'out',mul.id,'a');connect(p,bp.id,two.id,'value',mul.id,'b');connect(p,bp.id,mul.id,'value',bo.node.id,'in');
  let restored=deserializeProject(serializeProject(p)),r=await new RuntimeEngine(restored).evaluate(),value=r.values[restored.rootPatchId+':'+A.id+':'+ao.portId];
  return {ok:value===6,value,patches:Object.keys(restored.patches).length};
}catch(e){return {ok:false,error:String(e?.message||e)}}};

(async()=>{let i=await native.appInfo?.();if(i?.version)$('#versionBadge').textContent=i.version;let a=localStorage.getItem('node-vibe-autosave-v2');if(a)try{restore(a);log('Session restaurée.','success')}catch{}render();log('No-de Vibe Designer 0.8.0 · moteur prêt.','success');let self=await window.__nodeVibeSelfTest();log(self.ok?'Auto-test boîtes imbriquées · PASS ('+self.value+')':'Auto-test boîtes imbriquées · ÉCHEC · '+(self.error||self.value),self.ok?'success':'error');requestAnimationFrame(frame)})();
