
export const NODE_GROUPS = [
 ["Interaction / corps",[["Pointer / Souris","pointer"],["Baleine interactive","whale"],["Blob organique","blob"],["Tracking / points","tracking"],["Body Clone / Ombre","bodyclone"]]],
 ["Magic FX",[["Threshold","threshold"],["Ghost","ghost"],["Miroir","mirror"],["Ombre miroir","shadow"],["Transform","transform"],["Composite","composite"],["Trou noir","blackhole"]]],
 ["Vidéo / caméra",[["Caméra live","camera"],["Remote Camera","remote-camera"],["Fichier vidéo","videofile"],["Retour vidéo régie","videoreturn"],["Mapping vidéo","mapping"],["NDI Out (relais natif)","ndi-out"],["Anaglyphe","anaglyph"]]],
 ["Shaders / visuels",[["Shader Lab","shader"],["Creative FX","creativefx"],["Storm Forge","storm"],["Bending Lab","bending"],["Transmute","transmute"]]],
 ["Code / génératif",[["Processing / p5.js","p5"],["TouchDesigner tools","td"],["Mini Isadora","isadora"],["Sketch Lab","sketch"]]],
 ["Audio",[["Audio Lab","audio"],["Filtre audio","audiofilter"],["Delay audio","audiodelay"],["FFT audio","audiofft"],["Organic Audio","organicaudio"],["Mémo sonore","soundmemo"]]],
 ["Logique",[["Nombre","number"],["Booléen","boolean"],["Texte","text"],["Addition","add"],["Multiplication","multiply"],["Lissage","smooth"],["Comparaison","compare"],["Feedback","feedback"],["Timer","timer"]]],
 ["Contrôle scène",[["MIDI Hub","midi"],["OSC","osc"],["Art-Net / DMX","dmx"],["Control surfaces","surface"],["Input Mapper","inputmapper"],["Stage I/O","stageio"]]],
 ["Arduino / devices",[["AutoCode / Arduino IDE","arduino"],["ESP32 / Wemos","esp"],["Servos","servo"],["RFID / QR","rfid"],["Capteurs","sensors"]]],
 ["Passerelles",[["TWOZERO / TD Vibe","twozero"],["Chataigne Bridge","chataigne"],["Millumin Bridge","millumin"],["TouchDesigner Bridge","touchdesigner"],["Isadora Bridge","isadorabridge"],["Max/MSP Bridge","max"],["Pure Data Bridge","pd"],["SuperCollider Bridge","supercollider"]]],
 ["Projet / automation",[["Sous-patch","subpatch"],["Show Importer","showimport"],["Automation","automation"],["Dream Engine","dream"],["Data Lab","datalab"],["Universal Wire","universal"],["Connectors","connectors"]]],
 ["Mobile / device",[["Caméra avant","phone-camera-front"],["Caméra arrière","phone-camera-back"],["Micro","phone-mic"],["Écran tactile","touch"],["Multitouch","multitouch"],["Gyroscope","gyro"],["Accéléromètre","accelerometer"],["Orientation","orientation"],["GPS","gps"],["Haptique","haptics"],["Réseau / Wi-Fi","wifi"],["Bluetooth","bluetooth"]]]
];

export function spec(type){
  const m={
    camera:["Caméra live",["video","tracking","out"]],
    "remote-camera":["Remote Camera",["video","status","out"]],
    "ndi-out":["NDI Out (relais natif)",["video","status"]],
    pointer:["Pointer / Souris",["x","y","speed"]],
    whale:["Baleine interactive",["x","y","speed","out"]],
    blob:["Blob organique",["x","y","size","out"]],
    threshold:["Threshold",["video","threshold","out"]],
    ghost:["Ghost",["video","amount","out"]],
    mirror:["Miroir",["video","out"]],
    bodyclone:["Body Clone / Ombre",["video","threshold","out"]],
    videoreturn:["Retour vidéo régie",["video","status","out"]],
    mapping:["Mapping vidéo 2D",["video","scale","out"]],
    tracking:["Tracking / points",["points","curve","out"]],
    shader:["Shader Lab",["texture","glsl","out"]],
    anaglyph:["Anaglyphe",["video","depth","out"]],
    creativefx:["Creative FX",["video","amount","out"]],
    storm:["Storm Forge",["video","amount","out"]],
    bending:["Bending Lab",["video","amount","out"]],
    transmute:["Transmute",["video","amount","out"]],
    p5:["Processing / p5.js",["sketch","params","out"]],
    midi:["MIDI Hub",["device","CC","gate"]],
    osc:["OSC",["host","address","value"]],
    dmx:["Art-Net / DMX",["universe","address","value"]],
    surface:["Control Surface",["in","status","out"]],
    inputmapper:["Input Mapper",["value","out min","out max","out"]],
    stageio:["Stage I/O",["in","route","out"]],
    subpatch:["Sous-patch",["in","params","out"]],
    automation:["Automation",["speed","phase","value"]],
    datalab:["Data Lab",["value","scale","out"]],
    universal:["Universal Wire",["in","out"]],
    connectors:["Connectors",["in","status","out"]],
    audio:["Audio Lab",["in","process","out"]],
    audiofilter:["Filtre audio",["freq","q","level"]],
    audiodelay:["Delay audio",["time","feedback","level"]],
    audiofft:["FFT audio",["level","peak","bins"]],
    number:["Nombre",["value"]],
    add:["Addition",["a","b","value"]],
    smooth:["Lissage",["in","value"]],
    compare:["Comparaison",["a","b","result"]],
    boolean:["Booléen",["value"]],
    text:["Texte",["value"]],
    timer:["Timer",["start","time","done"]],
    feedback:["Feedback",["in","out"]],
    blackhole:["Trou noir",["speed","size","visual"]],
    transform:["Transform",["visual","scale","rotation","out"]],
    composite:["Composite",["base","overlay","out"]],
    shadow:["Ombre miroir",["video","threshold","out"]],
    videofile:["Fichier vidéo",["video","time","out"]],
    multiply:["Multiplication",["a","b","value"]],
    organicaudio:["Organic Audio",["in","reactive","out"]],
    soundmemo:["Mémo sonore",["record","tag","out"]],
    arduino:["Arduino / Serial",["command","trigger","status"]],
    esp:["ESP32 / Wemos Serial",["command","trigger","status"]],
    servo:["Servo / Serial",["channel","angle","speed","trigger","status"]],
    rfid:["RFID / QR Serial",["tag","present","raw"]],
    sensors:["Capteurs génériques",["sensor","value","status"]],
    twozero:["TWOZERO / TD Bridge",["value","trigger","status"]],
    chataigne:["Chataigne Bridge",["value","trigger","status"]],
    millumin:["Millumin Bridge",["value","trigger","status"]],
    touchdesigner:["TouchDesigner Bridge",["value","trigger","status"]],
    isadorabridge:["Isadora Bridge",["value","trigger","status"]],
    max:["Max/MSP Bridge",["value","trigger","status"]],
    pd:["Pure Data Bridge",["value","trigger","status"]],
    supercollider:["SuperCollider Bridge",["value","trigger","status"]],
    "phone-camera-front":["Caméra avant",["video","device","out"]],
    "phone-camera-back":["Caméra arrière",["video","device","out"]],
    "phone-mic":["Micro téléphone",["audio","level","out"]],
    touch:["Écran tactile",["x","y","pressure"]],
    multitouch:["Multitouch",["touches","gesture","out"]],
    gyro:["Gyroscope",["alpha","beta","gamma"]],
    accelerometer:["Accéléromètre",["x","y","z"]],
    orientation:["Orientation",["portrait","landscape","angle"]],
    gps:["GPS",["lat","lon","accuracy"]],
    haptics:["Haptique",["pattern","duration","trigger"]],
    wifi:["Wi-Fi",["network","latency","out"]],
    bluetooth:["Bluetooth",["device","service","characteristic"]]
  };
  return m[type] || [type,["input","process","output"]];
}
